### ISSUE TITLE
Unable to convert CTAS statements to use external storage

### ISSUE THREAD

**Issue by jscott0918** [dharmeshkakadia/tpcds-datagen-as-hive-query#4]
The CTAS statements used to create ~half of the ORC tables do not support using an external (non-primary) storage location.

Is there any alternative to convert these and still get relevant performance data from the queries? [Link to a statement in question](https://github.com/dharmeshkakadia/tpcds-hdinsight/blob/7c4f457d0e4d1a983366bf4e2897538d4306241c/ddl/createAllORCTables.hql#L618)

**Comment by dharmeshkakadia** [comment]
as I mentioned https://github.com/hdinsight/tpcds-hdinsight/issues/3#issuecomment-326123149 you should use location on the database and all the tables created within that would inherit the location. 
Does that not work for you ?

**Comment by dharmeshkakadia** [comment]
The suggestion worked as per https://github.com/hdinsight/tpcds-hdinsight/issues/5
